export const STORE_LOGIN_DATA = "STORE_LOGIN_DATA"
export const CLEAR_LOGIN_DATA = "CLEAR_LOGIN_DATA"
export const SETAPP_VERSION = "SETAPP_VERSION"
export const DEMO_LOGIN = "DEMO_LOGIN"
export const SET_LOGIN_FLAG = "SET_LOGIN_FLAG"

export const CITY_WALLET_AMOUNT = "CITY_WALLET_AMOUNT"

export const SET_BANNERS_HOMEPAGE = "SET_BANNERS_HOMEPAGE"
export const SET_AVAILABLE_BRAND_HOMEPAGE = "SET_AVAILABLE_BRAND_HOMEPAGE"
export const SET_ICONIC_BRAND_HOMEPAGE = "SET_ICONIC_BRAND_HOMEPAGE"
export const SET_SHOPINSHOP_BRAND_HOMEPAGE = "SET_SHOPINSHOP_BRAND_HOMEPAGE"
export const SET_PROMOS = "SET_PROMOS"
export const CLEAR_HOME_DATA = "CLEAR_HOME_DATA"
export const STORE_CITIES_HOMEPAGE = "STORE_CITIES_HOMEPAGE"

export const SET_ALL_BRAND = "SET_ALL_BRAND"
export const SET_FILTERED_BRAND = "SET_FILTERED_BRAND"
export const SET_COMING_SOON_BRAND = "SET_COMING_SOON_BRAND"
export const CLEAR_ALL_BRAND = "CLEAR_ALL_BRAND"

export const STORE_ORDER_LIST = "STORE_ORDER_LIST"
export const CLEAR_ORDER_LIST_DATA = "CLEAR_ORDER_LIST_DATA"

export const SET_BANNERS_STORE_BY_CITY = "SET_BANNERS_STORE_BY_CITY"
export const SET_MAIN_CATEGORIES = "SET_MAIN_CATEGORIES"
export const SET_GENDER = "SET_GENDER"
export const SET_AVAILABLE_BRANDS_BY_CITY = "SET_AVAILABLE_BRANDS_BY_CITY"
export const SET_CATEGORIES = "SET_CATEGORIES"
export const SET_MINIMUN_ORDER_PRICE = "SET_MINIMUN_ORDER_PRICE"
export const CLEAR_STORE_BY_CITY_DATA = "CLEAR_STORE_BY_CITY_DATA"

export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS"
export const SET_NOTIFICATIONS_UNREAD_COUNT = "SET_NOTIFICATIONS_UNREAD_COUNT"
export const SET_TOTAL_NOTIFICATION_PAGINATION = "SET_TOTAL_NOTIFICATION_PAGINATION"
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS"

export const SET_PURCHASE_HISTORY = "SET_PURCHASE_HISTORY"
export const CLEAR_PURCHASE_HISTORY_DATA = "CLEAR_PURCHASE_HISTORY_DATA"

export const SET_SHIPPING_ADDRESS = "SET_SHIPPING_ADDRESS"
export const SET_DEFAULT_ADDRESS = "SET_DEFAULT_ADDRESS"

export const SET_CART_ITEMS = "SET_CART_ITEMS"
export const SET_CART_TOTAL_PRICE_DETAILS = "SET_CART_TOTAL_PRICE_DETAILS"
export const SET_CART_COUNT_DATA = "SET_CART_COUNT_DATA"
export const CLEAR_CART_DATA = "CLEAR_CART_DATA"

export const SET_APP_ACTIVITY = "SET_APP_ACTIVITY"
export const CLEAR_APP_ACTIVITY = "CLEAR_APP_ACTIVITY"
export const SET_PRODUCT_FILTER = "SET_PRODUCT_FILTER"
export const SET_MYFEED_FILTER = "SET_MYFEED_FILTER"
export const SET_APP_LOGO = "SET_APP_LOGO"
export const CLEAR_PRODUCT_FILTER = "CLEAR_PRODUCT_FILTER"

export const SET_AVAILCREDIT_MODAL ="SET_AVAILCREDIT_MODAL"

export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST"
export const SET_PRODUCT_LIST_VIEW_TYPE = "SET_PRODUCT_LIST_VIEW_TYPE"
export const SET_PRODUCT_LIST_LAST_OFFSET = "SET_PRODUCT_LIST_LAST_OFFSET"
export const SET_LAST_PRODUCT_STATE = "SET_LAST_PRODUCT_STATE"
export const SET_LAST_PRODUCT_FILTER = "SET_LAST_PRODUCT_FILTER"
export const CLEAR_PRODUCT_LIST_DATA = "CLEAR_PRODUCT_LIST_DATA"


export const SET_WISHLIST_COUNT = "SET_WISHLIST_COUNT"
export const CLEAR_WISHLIST_COUNT = "CLEAR_WISHLIST_COUNT"

export const SET_CREDIT_AGENCIES = "SET_CREDIT_AGENCIES"
export const SET_RUPIFI_CREDIT_LIMIT = "SET_RUPIFI_CREDIT_LIMIT"
export const SET_RUPIFI_CREDIT_BALANCE = "SET_RUPIFI_CREDIT_BALANCE"
export const SET_RUPIFI_ACCOUNT_STATUS = "SET_RUPIFI_ACCOUNT_STATUS"
export const SET_RUPIFI_MARCHANT_ID = "SET_RUPIFI_MARCHANT_ID"
export const SET_RUPIFI_SOA_URL = "SET_RUPIFI_SOA_URL"
export const SET_RUPIFI_REPAYMENT_URL = "SET_RUPIFI_REPAYMENT_URL"
export const CLEAR_CREDIT_AGENCIES = "CLEAR_CREDIT_AGENCIES"
